wip

diff --git a/.github/workflows/valid-style.yml b/.github/workflows/valid-style.yml
--- a/.github/workflows/valid-style.yml
+++ b/.github/workflows/valid-style.yml
@@ -87,3 +87,35 @@ jobs:
           spack -d bootstrap now --dev
           spack style -t black
           spack unit-test -V
+  import-check:
+    runs-on: ubuntu-latest
+    steps:
+    - uses: julia-actions/setup-julia@v2
+      with:
+        version: '1.10'
+    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
+      with:
+        ref: ${{ github.event.pull_request.base.sha }}
+        path: old
+    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
+      with:
+        path: new
+    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
+      with:
+        repository: haampie/circular-import-fighter
+        path: circular-import-fighter
+    - run: |
+        cd circular-import-fighter
+        make SPACK_ROOT=../old
+        edges_before=$(grep -oP 'edges to delete: \K\d+' solution)
+        make clean-graph
+        make SPACK_ROOT=../new
+        edges_after=$(grep -oP 'edges to delete: \K\d+' solution)
+        if [ $edges_after -gt $edges_before ]; then
+          echo "Import check failed: $edges_after < $edges_before"
+          exit 1
+        elif [ $edges_after -lt $edges_before ]; then
+          echo "Import check passed: $edges_after < $edges_before"
+        else
+          echo "Import check passed: $edges_after == $edges_before"
+        fi
